# Generated by Django 6.1.1 on 2026-09-10 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(choices=[('JHTET', 'JHTET'), ('CTET', 'CTET'), ('JSSC', 'JSSC'), ('IGNOU', 'IGNOU'), ('OTHER', 'Other')], default='JHTET', max_length=20)),
                ('paper', models.CharField(choices=[('PAPER_I', 'Paper I'), ('PAPER_II', 'Paper II')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyllabusTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('unit', models.CharField(blank=True, max_length=200)),
                ('topic', models.CharField(max_length=250)),
                ('subtopic', models.TextField(blank=True)),
                ('source_page', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='syllabus.syllabus')),
            ],
        ),
    ]
