# Generated by Django 6.1.1 on 2026-09-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(choices=[('JHTET', 'JHTET'), ('CTET', 'CTET'), ('JSSC', 'JSSC'), ('IGNOU', 'IGNOU'), ('OTHER', 'Other')], max_length=20)),
                ('paper', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(blank=True, max_length=150)),
                ('question_text', models.TextField()),
                ('question_text_hindi', models.TextField(blank=True)),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('correct_answer', models.CharField(max_length=1)),
                ('explanation', models.TextField(blank=True)),
                ('explanation_hindi', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('EN', 'English'), ('HI', 'Hindi'), ('BILINGUAL', 'Bilingual')], default='BILINGUAL', max_length=10)),
                ('difficulty', models.CharField(default='Medium', max_length=20)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
