# Generated by Django 6.1.1 on 2026-09-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('exam', models.CharField(choices=[('JHTET', 'JHTET'), ('CTET', 'CTET'), ('JSSC', 'JSSC'), ('IGNOU', 'IGNOU'), ('OTHER', 'Other')], max_length=20)),
                ('paper', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('total_questions', models.PositiveIntegerField(default=30)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(blank=True, related_name='tests', to='engine.question')),
            ],
        ),
    ]
