# Generated by Django 6.1.1 on 2026-09-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subtopic',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
